"""
scripts/compact_wire_prototype.py -- BI Token Optimization Program, Phase
5D: compact provenance wire PROTOTYPE + round-trip proof. Zero provider
calls. NOT wired into fast_analysis.py/extractor.py; NOT active in any
production path.

Design (per the task's own conceptual pipeline):

    CURRENT SOURCE/PROVENANCE
            |
    deterministic short-ID registry   (this module, built by BI, offline)
            |
    MODEL WIRE FORMAT                 (what the model would emit, live)
            |
    deterministic expansion adapter   (this module)
            |
    EXACT EXISTING FastAnalysisResult / extraction representation

Because no live call is permitted this phase, the "model wire format" step
is stood in for by COMPACTING real historical (already-verbose) output and
then EXPANDING it back -- proving the registry + adapter round-trip
losslessly BEFORE ever asking a live model to speak this format. The
model must never invent an ID: every ID a compact wire format could
contain is drawn from a registry BI builds deterministically from the
document's own source markers, never from model output.

No document/RFP/proposal text is printed by this module's CLI beyond
short, explicitly-bounded samples; --json output contains full evidence
excerpts only because that is the artifact's own already-persisted
content being round-tripped, never anything freshly generated here.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Section 3: canonical source identity
# ---------------------------------------------------------------------------
# Verified against real historical output (fast_analysis_facts.json /
# stage_a_document_facts.json): every source_refs[] entry's distinct
# key-sets are subsets of exactly these four fields. `excerpt` is
# deliberately excluded from identity -- it is evidence TEXT, not a
# coordinate, and two different excerpts from the same coordinate must
# still resolve to the same source identity.
_IDENTITY_FIELDS = ("source_doc", "page", "sheet", "section")


def canonical_source_identity(ref: dict) -> tuple:
    """A hashable, deterministic identity for one source_refs[] entry,
    excluding excerpt. Missing fields normalize to None (never KeyError),
    matching real historical data where some refs omit page/sheet/section
    entirely rather than nulling them."""
    return tuple(ref.get(field) for field in _IDENTITY_FIELDS)


# ---------------------------------------------------------------------------
# Section 5: deterministic source-ID registry -- built by BI, never by the
# model. Simple ordinal IDs (S1, S2, ...) per instruction 3: "Simple
# deterministic ordinal IDs may be preferable" -- no opaque hash, since an
# ordinal gives no advantage here (uniqueness comes from the dict key, not
# the ID's own bytes) and is shorter on the wire.
# ---------------------------------------------------------------------------

class SourceRegistry:
    """Deterministic identity<->short-ID bijection. Construction order is
    the only source of ID assignment, so building the SAME registry from
    the SAME identities in the SAME order always yields the SAME IDs
    (stable inside one request/result, per instruction 3)."""

    def __init__(self):
        self._id_by_identity: dict[tuple, str] = {}
        self._identity_by_id: dict[str, tuple] = {}

    def register(self, ref: dict) -> str:
        identity = canonical_source_identity(ref)
        existing = self._id_by_identity.get(identity)
        if existing is not None:
            return existing
        new_id = f"S{len(self._id_by_identity) + 1}"
        self._id_by_identity[identity] = new_id
        self._identity_by_id[new_id] = identity
        return new_id

    def id_for(self, ref: dict) -> str | None:
        return self._id_by_identity.get(canonical_source_identity(ref))

    def identity_for(self, source_id: str) -> tuple | None:
        return self._identity_by_id.get(source_id)

    def to_wire(self) -> dict:
        """{"S1": {"source_doc": ..., "page": ..., "sheet": ..., "section": ...}, ...}
        -- the registry as it would be supplied to (never generated by) the model."""
        return {sid: dict(zip(_IDENTITY_FIELDS, identity))
                for sid, identity in self._identity_by_id.items()}

    def __len__(self) -> int:
        return len(self._id_by_identity)


def build_registry_from_facts(obj) -> SourceRegistry:
    """Deterministic, order-stable traversal: walks the facts structure in
    its own natural (already-deterministic, already-persisted) order and
    registers every source_refs[] entry encountered. Two identical
    coordinates anywhere in the document -- even across different object
    families -- collapse to the same ID; two different coordinates always
    get different IDs (collision-proof by construction: the dict key IS
    the full identity tuple)."""
    registry = SourceRegistry()

    def _walk(o):
        if isinstance(o, dict):
            refs = o.get("source_refs")
            if isinstance(refs, list):
                for ref in refs:
                    if isinstance(ref, dict):
                        registry.register(ref)
            for v in o.values():
                _walk(v)
        elif isinstance(o, list):
            for item in o:
                _walk(item)

    _walk(obj)
    return registry


# ---------------------------------------------------------------------------
# Section 9: evidence-dictionary eligibility. Only source_refs[].excerpt is
# documented (fast_analysis.py's _SOURCE_REF_RULES / extractor.py's
# STAGE_A_FACT_EXTRACTION_PROMPT) as "verbatim quote from text" --
# genuinely SOURCE-DERIVED and pre-identifiable BEFORE the model runs,
# since the same source coordinate deterministically has the same
# underlying text. Every other free-text field (description,
# original_value, source_fact, notes, summary, ...) is the model's own
# normalization/paraphrase per those same schemas' own instructions
# ("Concise factual normalization", "exact criterion... as stated" is
# closer but still model-selected) -- classified MODEL_GENERATED and
# explicitly NOT eligible for a preassigned dictionary ID.
# ---------------------------------------------------------------------------
EVIDENCE_FIELD_CLASSIFICATION = {
    "excerpt": "SOURCE_DERIVED_PREIDENTIFIABLE",
    "original_value": "MODEL_GENERATED",
    "description": "MODEL_GENERATED",
    "source_fact": "MODEL_GENERATED",
    "notes": "MODEL_GENERATED",
    "summary": "MODEL_GENERATED",
    "raw_wording": "MIXED",  # documented as "verbatim or near-verbatim" -- not guaranteed exact
}


class EvidenceRegistry:
    """Same bijective-ID pattern as SourceRegistry, restricted to exact-
    duplicate SOURCE_DERIVED_PREIDENTIFIABLE text only (excerpt fields)."""

    def __init__(self):
        self._id_by_text: dict[str, str] = {}
        self._text_by_id: dict[str, str] = {}

    def register(self, text: str) -> str:
        existing = self._id_by_text.get(text)
        if existing is not None:
            return existing
        new_id = f"E{len(self._id_by_text) + 1}"
        self._id_by_text[text] = new_id
        self._text_by_id[new_id] = text
        return new_id

    def id_for(self, text: str) -> str | None:
        return self._id_by_text.get(text)

    def text_for(self, evidence_id: str) -> str | None:
        return self._text_by_id.get(evidence_id)

    def to_wire(self) -> dict:
        return dict(self._text_by_id)

    def __len__(self) -> int:
        return len(self._id_by_text)


def build_evidence_registry_from_facts(obj, min_duplicate_count: int = 2) -> EvidenceRegistry:
    """Only registers excerpt text that ACTUALLY repeats >= min_duplicate_count
    times in this document (a dictionary entry for a value used once is pure
    overhead, never a saving)."""
    from collections import Counter
    counts: Counter = Counter()

    def _count(o):
        if isinstance(o, dict):
            refs = o.get("source_refs")
            if isinstance(refs, list):
                for ref in refs:
                    if isinstance(ref, dict):
                        excerpt = ref.get("excerpt")
                        if isinstance(excerpt, str) and excerpt:
                            counts[excerpt] += 1
            for v in o.values():
                _count(v)
        elif isinstance(o, list):
            for item in o:
                _count(item)

    _count(obj)
    registry = EvidenceRegistry()
    for text, n in counts.items():
        if n >= min_duplicate_count:
            registry.register(text)
    return registry


# ---------------------------------------------------------------------------
# Sections 7/10/11: compact <-> expand adapter. Structural, lossless,
# deterministic. Fail-closed validation lives in `expand_compact_ref`.
# ---------------------------------------------------------------------------

class CompactWireError(ValueError):
    """Raised by expansion on any malformed/unknown compact input -- never
    silently repaired (instruction 19: 'No silent repair')."""


_FULL_REF_KEYS = ("source_doc", "page", "sheet", "section", "excerpt")


def compact_source_ref(ref: dict, source_registry: SourceRegistry,
                       evidence_registry: EvidenceRegistry | None = None) -> dict:
    """One source_refs[] entry -> its compact wire form. Always includes
    the resolved source_id. The excerpt is carried as EXACTLY ONE of two
    unambiguous keys -- "eid" (a dictionary reference) or "e" (inline
    text) -- never overloaded into one field, so expansion never has to
    guess which case it is looking at (most excerpts are NOT exact
    duplicates -- see Phase 5C, 282 of 392 evidence occurrences unique --
    so "e" inline remains the common case).

    Real historical output (Phase 5D verification) shows a small number
    of refs (3 of 239 in the V4 artifact) omit a key ENTIRELY rather than
    setting it null (e.g. no "excerpt" key at all, not "excerpt": null).
    "k" records exactly which of the 5 possible keys were present in the
    ORIGINAL ref, but ONLY when that set differs from the full/standard
    pattern -- zero extra bytes for the ~98.7% common case, and exact
    key-presence fidelity (not just value fidelity) for the rest."""
    sid = source_registry.id_for(ref)
    if sid is None:
        raise CompactWireError(f"source ref has no registry entry: {ref!r}")
    compact = {"s": sid}
    present_keys = tuple(k for k in _FULL_REF_KEYS if k in ref)
    if present_keys != _FULL_REF_KEYS:
        compact["k"] = present_keys
    if "excerpt" in ref:
        excerpt = ref.get("excerpt")
        if excerpt:
            eid = evidence_registry.id_for(excerpt) if evidence_registry else None
            if eid is not None:
                compact["eid"] = eid
            else:
                compact["e"] = excerpt
        else:
            compact["e"] = excerpt  # key was present but falsy (None/"") -- preserve exactly
    return compact


def expand_compact_ref(compact: dict, source_registry: SourceRegistry,
                       evidence_registry: EvidenceRegistry | None = None) -> dict:
    """Fail-closed: unknown source ID, unknown evidence ID, or an
    unexpected/ambiguous shape all raise CompactWireError rather than
    guessing (instruction 19: 'No silent repair')."""
    if not isinstance(compact, dict) or "s" not in compact:
        raise CompactWireError(f"malformed compact source ref: {compact!r}")
    allowed_keys = {"s", "e", "eid", "k"}
    if set(compact.keys()) - allowed_keys:
        raise CompactWireError(f"compact source ref has unexpected keys: {compact!r}")
    if "e" in compact and "eid" in compact:
        raise CompactWireError(f"compact source ref has both inline and dictionary evidence: {compact!r}")
    identity = source_registry.identity_for(compact["s"])
    if identity is None:
        raise CompactWireError(f"unknown source id (not in registry, model-invented?): {compact['s']!r}")
    full_identity = dict(zip(_IDENTITY_FIELDS, identity))

    if "eid" in compact:
        if evidence_registry is None:
            raise CompactWireError(f"evidence id {compact['eid']!r} present but no evidence registry supplied")
        resolved = evidence_registry.text_for(compact["eid"])
        if resolved is None:
            raise CompactWireError(f"unknown evidence id (not in registry, model-invented?): {compact['eid']!r}")
        excerpt_value = resolved
    else:
        excerpt_value = compact.get("e")

    present_keys = compact.get("k", _FULL_REF_KEYS)
    if not isinstance(present_keys, (list, tuple)) or any(k not in _FULL_REF_KEYS for k in present_keys):
        raise CompactWireError(f"malformed key-presence marker: {compact.get('k')!r}")
    expanded = {}
    for field in _IDENTITY_FIELDS:
        if field in present_keys:
            expanded[field] = full_identity[field]
    if "excerpt" in present_keys:
        expanded["excerpt"] = excerpt_value
    return expanded


def compact_facts(obj, source_registry: SourceRegistry, evidence_registry: EvidenceRegistry | None = None):
    """Recursively replaces every source_refs[] list with its compact
    form. Every other field is left byte-for-byte untouched -- this
    prototype only targets provenance representation (instruction 7's
    "smallest semantic change"), never requirement/criterion/clause
    content."""
    if isinstance(obj, dict):
        out = {}
        for k, v in obj.items():
            if k == "source_refs" and isinstance(v, list):
                out[k] = [compact_source_ref(r, source_registry, evidence_registry)
                         if isinstance(r, dict) else r for r in v]
            else:
                out[k] = compact_facts(v, source_registry, evidence_registry)
        return out
    if isinstance(obj, list):
        return [compact_facts(item, source_registry, evidence_registry) for item in obj]
    return obj


def expand_facts(obj, source_registry: SourceRegistry, evidence_registry: EvidenceRegistry | None = None):
    """The deterministic expansion adapter -- the ONLY place compact IDs
    are ever resolved back to full identities. Downstream consumers never
    see a compact ID; they receive exactly the pre-Phase-5D shape."""
    if isinstance(obj, dict):
        out = {}
        for k, v in obj.items():
            if k == "source_refs" and isinstance(v, list):
                out[k] = [expand_compact_ref(r, source_registry, evidence_registry)
                         if isinstance(r, dict) else r for r in v]
            else:
                out[k] = expand_facts(v, source_registry, evidence_registry)
        return out
    if isinstance(obj, list):
        return [expand_facts(item, source_registry, evidence_registry) for item in obj]
    return obj


def round_trip(original: dict, use_evidence_dictionary: bool = True) -> tuple[dict, bool, dict]:
    """Returns (expanded, is_exact_match, byte_report). Never mutates or
    persists `original`."""
    source_registry = build_registry_from_facts(original)
    evidence_registry = build_evidence_registry_from_facts(original) if use_evidence_dictionary else None
    compact = compact_facts(original, source_registry, evidence_registry)
    expanded = expand_facts(compact, source_registry, evidence_registry)
    is_exact = expanded == original
    original_bytes = len(json.dumps(original, sort_keys=True).encode("utf-8"))
    compact_bytes = len(json.dumps(compact, sort_keys=True).encode("utf-8"))
    registry_bytes = len(json.dumps(source_registry.to_wire(), sort_keys=True).encode("utf-8"))
    evidence_registry_bytes = (len(json.dumps(evidence_registry.to_wire(), sort_keys=True).encode("utf-8"))
                               if evidence_registry else 0)
    return expanded, is_exact, {
        "original_bytes": original_bytes,
        "compact_body_bytes": compact_bytes,
        "source_registry_bytes": registry_bytes,
        "evidence_registry_bytes": evidence_registry_bytes,
        "compact_total_bytes": compact_bytes + registry_bytes + evidence_registry_bytes,
        "source_identities": len(source_registry),
        "evidence_entries": len(evidence_registry) if evidence_registry else 0,
    }


# ---------------------------------------------------------------------------
# Section 8: short-key alias design study (measurement only -- never applied)
# ---------------------------------------------------------------------------

def alias_savings_study(obj, alias_map: dict[str, str]) -> list[dict]:
    """For each candidate key alias, measures real occurrence count and
    byte savings from this actual historical document -- classification
    is left to the caller/report, not automated here, since "explaining
    the alias to the model" cost is a prompt-design judgment, not
    something derivable from the data alone."""
    from collections import Counter
    counts: Counter = Counter()

    def _walk(o):
        if isinstance(o, dict):
            for k, v in o.items():
                counts[k] += 1
                _walk(v)
        elif isinstance(o, list):
            for item in o:
                _walk(item)

    _walk(obj)
    results = []
    for full, alias in alias_map.items():
        n = counts.get(full, 0)
        if n == 0:
            continue
        saved_per_occurrence = len(full.encode("utf-8")) - len(alias.encode("utf-8"))
        results.append({
            "full_name": full, "alias": alias, "occurrences": n,
            "bytes_saved": saved_per_occurrence * n,
        })
    return sorted(results, key=lambda r: r["bytes_saved"], reverse=True)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--facts-file", required=True, help="Historical facts JSON to replay")
    parser.add_argument("--no-evidence-dictionary", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    original = json.loads(Path(args.facts_file).read_text(encoding="utf-8"))
    expanded, is_exact, report = round_trip(original, use_evidence_dictionary=not args.no_evidence_dictionary)
    report["round_trip_exact"] = is_exact
    report["bytes_reduced"] = report["original_bytes"] - report["compact_total_bytes"]
    report["pct_reduced"] = (round(100 * report["bytes_reduced"] / report["original_bytes"], 1)
                             if report["original_bytes"] else None)

    if args.json:
        print(json.dumps(report, indent=2))
    else:
        for k, v in report.items():
            print(f"{k}: {v}")
    return 0 if is_exact else 1


if __name__ == "__main__":
    raise SystemExit(main())
